TestDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

blog/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
]

blog/models.py
import datetime

from django.db import models
from django.conf import settings
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Article(models.Model):
    article_title = models.CharField('name', max_length=200)
    article_text = models.TextField('текст')
    pub_date = models.DateTimeField('дата')

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('имя автора', max_length=50)
    comment_text = models.TextField('текст коммента', max_length=200)

    def __str__(self):
        return self.author_name

blog/views.py
from django.shortcuts import render
from django.urls import reverse

from .models import Article
from django.http import Http404, HttpResponseRedirect


def index(request):
    latest_articles_list = Article.objects.order_by('-pub_date')[:5]
    return render(request, 'blog/list.html', {'latest_articles_list': latest_articles_list})


def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Nothing here!")

    latest_comments_list = a.comment_set.order_by('-id')[:10]

    return render(request, 'blog/details.html', {'article': a, 'latest_comments_list':latest_comments_list})


def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Nothing here!")

    a.comment_set.create(author_name=request.POST['name'], comment_text=request.POST['text'])

    return HttpResponseRedirect(reverse('articles:detail', args=(a.id,)))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Blog{% endblock %}</title>
</head>
<body>

    {% block content %}{% endblock %}

</body>
</html>

templates/blog/details.html
{% extends 'base.html' %}

{% block title %}{{ article.article_title }}{% endblock %}

{% block content %}

    <h2>{{ article.article_title }}</h2>

    <p>{{ article.article_text }}</p>

    <em>{{ article.pub_date }}</em>

    <hr>

    {% if latest_comments_list %}

        {% for c in latest_comments_list %}
            <p>
                <strong>{{ c.author_name }}</strong>
                <p>{{ c.comment_text }}</p>
            </p>
        {% endfor %}
    {% endif %}


    <hr>

    <form action="{% url 'articles:leave_comment' article.id %}" method="post">

        {% csrf_token %}

        <input type="text" required placeholder="Your name" name="name"><br>
        <textarea name="text" required="" placeholder="Comment text" cols="30" rows="10"></textarea><br>

        <button type="submit">Leave comment</button>

    </form>

{% endblock %}

templates/blog/list.html
{% extends 'base.html' %}

{% block title %}Last art{% endblock %}

{% block content %}

    {% if latest_articles_list %}

        {% for a in latest_articles_list %}
            <a href="{% url 'articles:detail' a.id %}">{{ a.article_title }}</a>
        {% endfor %}

    {% else %}
        No articles
    {% endif %}

{% endblock %}